OpenAI_key = "sk-proj-oLcOvJbgx6nYKFJvMSlgT3BlbkFJVJuBre0NqpnKdmTgO7Jn"
DB_NAME = "postgres"
DB_USER = "postgres.nwecdrxfnogwxbfwauxw"
DB_PASS = "TeamIremboAI"
DB_HOST = "aws-0-eu-central-1.pooler.supabase.com"
DB_PORT = "5432"